export const DESCRIPTORS = {
    0x40: 'network_name_descriptor',
    0x41: 'service_list_descriptor',
    0x42: 'stuffing_descriptor',
    0x43: 'satellite_delivery_system_descriptor',
    0x44: 'cable_delivery_system_descriptor',
    0x45: 'VBI_data_descriptor',
    0x46: 'VBI_teletext_descriptor',
    0x47: 'bouquet_name_descriptor',
    0x48: 'service_descriptor',
    0x49: 'country_availability_descriptor',
    0x4A: 'linkage_descriptor',
    0x4B: 'NVOD_reference_descriptor',
    0x4C: 'time_shifted_service_descriptor',
    0x4D: 'short_event_descriptor',
    0x4E: 'extended_event_desciptor',
    0x4F: 'time_shifted_event_descriptor',
    0x50: 'component_descriptor',
    0x51: 'mosaic_descriptor',
    0x52: 'stream_identifier_descriptor',
    0x53: 'CA_identifier_descriptor',
    0x54: 'content_descriptor',
    0x55: 'parental_rating_descriptor',
    0x56: 'teletext_descriptor',
    0x57: 'telephone_descriptor',
    0x58: 'local_time_offset_descriptor',
    0x59: 'subtitling_descriptor',
    0x5A: 'terrestrial_delivery_system_descriptor',
    0x5B: 'multilingual_network_name_descriptor',
    0x5C: 'multilingual_bouquet_name_descriptor',
    0x5D: 'multilingual_service_name_descriptor',
    0x5E: 'multilingual_component_descriptor',
    0x5F: 'private_data_specifier_descriptor',
    0x60: 'service_move_descriptor',
    0x61: 'short_smoothing_buffer_descriptor',
    0x62: 'frequency_list_descriptor',
    0x63: 'partial_transport_stream_descriptor',
    0x64: 'data_broadcast_descriptor',
    0x65: 'scrambling_descriptor',
    0x66: 'data_broadcast_id_descriptor',
    0x67: 'transport_stream_descriptor',
    0x68: 'DSNG_descriptor',
    0x69: 'PDC_descriptor',
    0x6A: 'AC-3_descriptor',
    0x6B: 'ancillary_data_descriptor',
    0x6C: 'cell_list_descriptor',
    0x6D: 'cell_frequency_link_descriptor',
    0x6E: 'announcement_support_descriptor',
    0x6F: 'application_signalling_descriptor',
    0x70: 'adapation_field_data_descriptor',
    0x71: 'service_identifier_descriptor',
    0x72: 'service_availability_descriptor',
    0x73: 'default_authority_descriptor', // TS 102 323
    0x74: 'related_content_descriptor', // TS 102 323
    0x75: 'TVA_id_descriptor', // TS 102 323
    0x76: 'content_identifier_descriptor', // TS 102 323
    0x77: 'time_slice_fec_identifier_descriptor', // EN 301 192
    0x78: 'ECM_repetition_rate_descriptor', // EN 301 192
    0x79: 'S2_satellite_delivery_system_descriptor',
    0x7A: 'enhanced_AC-3_descriptor',
    0x7B: 'DTS_descriptor',
    0x7C: 'AAC_descriptor',
    0x7D: 'XAIT_location_descriptor',
    0x7E: 'FTA_content_management_descriptor',
    0x7F: 'extension_descriptor',
    // 0x80 - 0xFE: User defined
    // 0xFF: Forbidden
};
